import './globals.scss'
import type { Metadata } from 'next'
import { dir } from 'i18next'
import { detectLanguage } from '@/locales'
// import { Inter } from 'next/font/google'
import AppLayout from '@/components/AppLayout'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: {
        template: '%s | Khảo thí online',
        default: 'Khảo thí online', // a default is required when creating a template
    },
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const lng = detectLanguage()

  return (
    <html lang={lng} dir={dir(lng)}>
      <body>
          <AppLayout>{children}</AppLayout>
      </body>
    </html>
  )
}
